### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by OPilgrim** [deepfake-study/deepfake-multiLID#1]
Thank you so much for doing such a great job!
However, I found that the specific data sets used in the paper were not given in the github. Can those data sets be open source? After all, the results generated by the model are not guaranteed to be consistent every time. Hope to receive your reply soon!
In addition, there are multiple reference paths in the repository reporting errors, considering that the code is just open source, I hope to see more perfect and friendly code in the future.

**Comment by jS5t3r** [comment]
Thanks, yes, I am going to put the datasets online. 

Could u tell me some the errors?
