### ISSUE TITLE
Where is environment.yml?

### ISSUE THREAD

**Issue by uioo1** [deepfake-study/deepfake-multiLID#2]
I read your paper with great impression. Thanks for good work.
But there's no environment.yml file and also requirements.txt file is not type of yaml.

I renamed file and tried
`conda env create -f requiremnt.yaml`
it didn't work.

`pip install -r requirements.txt`
also didn't work

Colud you upload proper yaml file or requirements.txt?

**Comment by jS5t3r** [comment]
Hi, 

yes, this file was missing.  
I updated the repository accordingly. 

```
conda env create -f environment_all.yaml
```

Please, try this out and let me know.

**Comment by uioo1** [comment]
`
conda env create -f environment_all.yaml
`
still didn't work

`
pip install -r requirements_all.txt
`
didn't work

`
pip install -r requirements.txt
`
crashed by version issue because of huggingface_hub==0.13.4
so I deleted version of it and it worked.

I tried detect code and it's working.
But I'm confused about running custom dataset.
Shoud I make .csv file of custom dataset?

**Comment by jS5t3r** [comment]
thank you for the feedback. 

Not all datasets can be generated by gen.py!!!!!

Do you mean Laion5B? There is an own download provided by them.

**Comment by jS5t3r** [comment]
closed because of inactivity

**Comment by jS5t3r** [comment]
closed because of inactivity
